sudo: required
services:
  - docker

before_install:
  - docker build -t niketjsh/docker-react -f Dockerfile.dev .

script:
  - docker run niketjsh/docker-react npm run test --forceExit

deploy: 
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "bucket name contains in AWS"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"